# Data pre-processing
### Step 1: Import necessary libraries and load the dataset

In [24]:
import pandas as pd
import numpy as np

In [25]:
train = pd.read_csv ("data/train.csv")

### Step 2: Drop irrelevant columns

'PassengerId' and 'Name' are only identifiers and have no predictive value.

In [26]:
train = train.drop (columns = ['PassengerId', 'Name'])

train

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False
8689,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,False
8690,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,True
8691,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False
8692,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,True

### Step 3: Handle missing values

- numerical data use median imputation
- categorical/boolean data use mode imputation

In [27]:
# Split the columns into numerical or categorical
num_cols = ["Age", "RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]
cat_cols = ["HomePlanet", "CryoSleep", "Cabin", "Destination", "VIP"]

# Fill in missing values for numerical data
train [num_cols] = train [num_cols].fillna (train [num_cols].median ())

# Fill in missing values for categorical data
for col in cat_cols:
    train [col] = train [col].fillna (train [col].mode ()[0])

train

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False
8689,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,False
8690,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,True
8691,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False
8692,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,True

### Step 4: Convert boolean values into numerical values

In [28]:
train ["CryoSleep"] = train ["CryoSleep"].astype (int)
train ["VIP"] = train ["VIP"].astype (int)
train ["Transported"] = train ["Transported"].astype (int)

train

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,0,B/0/P,TRAPPIST-1e,39.0,0,0.0,0.0,0.0,0.0,0.0,0
1,Earth,0,F/0/S,TRAPPIST-1e,24.0,0,109.0,9.0,25.0,549.0,44.0,1
2,Europa,0,A/0/S,TRAPPIST-1e,58.0,1,43.0,3576.0,0.0,6715.0,49.0,0
3,Europa,0,A/0/S,TRAPPIST-1e,33.0,0,0.0,1283.0,371.0,3329.0,193.0,0
4,Earth,0,F/1/S,TRAPPIST-1e,16.0,0,303.0,70.0,151.0,565.0,2.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,0,A/98/P,55 Cancri e,41.0,1,0.0,6819.0,0.0,1643.0,74.0,0
8689,Earth,1,G/1499/S,PSO J318.5-22,18.0,0,0.0,0.0,0.0,0.0,0.0,0
8690,Earth,0,G/1500/S,TRAPPIST-1e,26.0,0,0.0,0.0,1872.0,1.0,0.0,1
8691,Europa,0,E/608/S,55 Cancri e,32.0,0,0.0,1049.0,0.0,353.0,3235.0,0
8692,Europa,0,E/608/S,TRAPPIST-1e,44.0,0,126.0,4688.0,0.0,0.0,12.0,1

### Step 5: Handle cabin

In [29]:
train [["Deck", "Num", "Side"]] = train ["Cabin"].str.split ("/", expand = True)
train = train.drop (columns = "Cabin")

train

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,Deck,Num,Side
0,Europa,0,TRAPPIST-1e,39.0,0,0.0,0.0,0.0,0.0,0.0,0,B,0,P
1,Earth,0,TRAPPIST-1e,24.0,0,109.0,9.0,25.0,549.0,44.0,1,F,0,S
2,Europa,0,TRAPPIST-1e,58.0,1,43.0,3576.0,0.0,6715.0,49.0,0,A,0,S
3,Europa,0,TRAPPIST-1e,33.0,0,0.0,1283.0,371.0,3329.0,193.0,0,A,0,S
4,Earth,0,TRAPPIST-1e,16.0,0,303.0,70.0,151.0,565.0,2.0,1,F,1,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,0,55 Cancri e,41.0,1,0.0,6819.0,0.0,1643.0,74.0,0,A,98,P
8689,Earth,1,PSO J318.5-22,18.0,0,0.0,0.0,0.0,0.0,0.0,0,G,1499,S
8690,Earth,0,TRAPPIST-1e,26.0,0,0.0,0.0,1872.0,1.0,0.0,1,G,1500,S
8691,Europa,0,55 Cancri e,32.0,0,0.0,1049.0,0.0,353.0,3235.0,0,E,608,S
8692,Europa,0,TRAPPIST-1e,44.0,0,126.0,4688.0,0.0,0.0,12.0,1,E,608,S

### Step 6: Convert categorical data into numerical data
- One-hot encoding

In [30]:
cat_cols = ["HomePlanet", "Destination", "Deck", "Side"]
train = pd.get_dummies (train, columns = cat_cols, drop_first = True)

train

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,Num,...,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,Deck_B,Deck_C,Deck_D,Deck_E,Deck_F,Deck_G,Deck_T,Side_S
0,0,39.0,0,0.0,0.0,0.0,0.0,0.0,0,0,...,False,True,True,False,False,False,False,False,False,False
1,0,24.0,0,109.0,9.0,25.0,549.0,44.0,1,0,...,False,True,False,False,False,False,True,False,False,True
2,0,58.0,1,43.0,3576.0,0.0,6715.0,49.0,0,0,...,False,True,False,False,False,False,False,False,False,True
3,0,33.0,0,0.0,1283.0,371.0,3329.0,193.0,0,0,...,False,True,False,False,False,False,False,False,False,True
4,0,16.0,0,303.0,70.0,151.0,565.0,2.0,1,1,...,False,True,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,0,41.0,1,0.0,6819.0,0.0,1643.0,74.0,0,98,...,False,False,False,False,False,False,False,False,False,False
8689,1,18.0,0,0.0,0.0,0.0,0.0,0.0,0,1499,...,True,False,False,False,False,False,False,True,False,True
8690,0,26.0,0,0.0,0.0,1872.0,1.0,0.0,1,1500,...,False,True,False,False,False,False,False,True,False,True
8691,0,32.0,0,0.0,1049.0,0.0,353.0,3235.0,0,608,...,False,False,False,False,False,True,False,False,False,True
8692,0,44.0,0,126.0,4688.0,0.0,0.0,12.0,1,608,...,False,True,False,False,False,True,False,False,False,True

### Step 7: Separate X and y

In [31]:
X = train.drop (columns = "Transported")
y = train ["Transported"]

### Step 8: Feature Scaling
- Z-score standardisation

In [32]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler ()
X_scaled = scaler.fit_transform (X)

# Model selection
### Logistic Regression (forward stepwise)

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_scaled = pd.DataFrame (X_scaled, columns = X.columns)

X_train, X_val, y_train, y_val = train_test_split (X_scaled, y, test_size = 0.2, random_state = 42)

features = list (X.columns)
selected_features = []
remaining_features = features.copy ()
best_score = 0

while len (remaining_features) > 0:
    scores = []

    for feature in remaining_features:
        current_features = selected_features + [feature]

        model = LogisticRegression (max_iter = 1000)
        model.fit (X_train [current_features], y_train)

        y_pred = model.predict (X_val [current_features])
        accuracy = accuracy_score (y_val, y_pred)
        
        scores.append ((accuracy, feature))
    
    scores.sort (reverse = True)
    best_new_score, best_feature = scores [0]

    if best_new_score <= best_score:
        break

    selected_features.append (best_feature)
    remaining_features.remove (best_feature)
    best_score = best_new_score

print ("Final accuracy score: ", best_score)
print ("Selected features: ", selected_features)

X_train.head

Final accuracy score:  0.7889591719378953
Selected features:  ['CryoSleep', 'FoodCourt', 'VRDeck', 'Spa', 'RoomService', 'Deck_E', 'Deck_F', 'Deck_T']

<bound method NDFrame.head of       CryoSleep       Age       VIP  RoomService  FoodCourt  ShoppingMall  \
2333  -0.732770 -0.055109 -0.153063    -0.333105  -0.246559     -0.283579
2589  -0.732770 -0.822163 -0.153063    -0.333105   0.467861     -0.231737
8302   1.364685 -0.055109 -0.153063    -0.333105  -0.281027     -0.283579
8177  -0.732770 -0.612966 -0.153063    -0.333105  -0.279773      0.199721
500    1.364685  0.502749 -0.153063    -0.333105  -0.281027     -0.283579
...         ...       ...       ...          ...        ...           ...
5734  -0.732770 -0.752431 -0.153063    -0.311908  -0.279773     -0.042765
5191  -0.732770  1.478999 -0.153063     0.711588  -0.281027     -0.233409
5390  -0.732770 -0.473502 -0.153063    -0.093885  -0.281027      0.512444
860   -0.732770  0.363284 -0.153063     0.240720  -0.281027      2.435609
7270  -0.732770 -0.055109 -0.153063    -0.322506   0.025422     -0.283579

           Spa    VRDeck       Num  HomePlanet_Europa  ...  \
2333  0.312227 -0.263003  0.257877          -0.569867  ...
2589 -0.270626 -0.263003 -0.056142          -0.569867  ...
8302 -0.270626 -0.263003 -0.541982           1.754795  ...
8177  0.596546 -0.263003  2.363185          -0.569867  ...
500  -0.270626 -0.263003 -1.156195           1.754795  ...
...        ...       ...       ...                ...  ...
5734  0.271356 -0.263003  0.759517          -0.569867  ...
5191  0.406408  0.114401  0.907639          -0.569867  ...
5390 -0.270626 -0.240077  1.166359          -0.569867  ...
860  -0.270626 -0.263003 -0.814527          -0.569867  ...
7270 -0.267072  5.051525 -0.692079           1.754795  ...

      Destination_PSO J318.5-22  Destination_TRAPPIST-1e    Deck_B    Deck_C  \
2333                  -0.317487                 0.652521 -0.313741 -0.306610
2589                  -0.317487                 0.652521 -0.313741 -0.306610
8302                  -0.317487                -1.532519 -0.313741  3.261474
8177                  -0.317487                 0.652521 -0.313741 -0.306610
500                   -0.317487                -1.532519 -0.313741  3.261474
...                         ...                      ...       ...       ...
5734                  -0.317487                 0.652521 -0.313741 -0.306610
5191                  -0.317487                 0.652521 -0.313741 -0.306610
5390                   3.149739                -1.532519 -0.313741 -0.306610
860                   -0.317487                 0.652521 -0.313741 -0.306610
7270                  -0.317487                -1.532519 -0.313741  3.261474

        Deck_D    Deck_E    Deck_F    Deck_G   Deck_T    Side_S
2333 -0.241218 -0.334759 -0.688215  1.466943 -0.02399  0.968181
2589 -0.241218 -0.334759  1.453035 -0.681690 -0.02399 -1.032865
8302 -0.241218 -0.334759 -0.688215 -0.681690 -0.02399  0.968181
8177 -0.241218 -0.334759  1.453035 -0.681690 -0.02399 -1.032865
500  -0.241218 -0.334759 -0.688215 -0.681690 -0.02399 -1.032865
...        ...       ...       ...       ...      ...       ...
5734 -0.241218 -0.334759 -0.688215  1.466943 -0.02399  0.968181
5191 -0.241218 -0.334759  1.453035 -0.681690 -0.02399  0.968181
5390 -0.241218 -0.334759  1.453035 -0.681690 -0.02399 -1.032865
860  -0.241218 -0.334759  1.453035 -0.681690 -0.02399 -1.032865
7270 -0.241218 -0.334759 -0.688215 -0.681690 -0.02399 -1.032865

[6954 rows x 21 columns]>

In [34]:
X_train

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Num,HomePlanet_Europa,...,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,Deck_B,Deck_C,Deck_D,Deck_E,Deck_F,Deck_G,Deck_T,Side_S
2333,-0.732770,-0.055109,-0.153063,-0.333105,-0.246559,-0.283579,0.312227,-0.263003,0.257877,-0.569867,...,-0.317487,0.652521,-0.313741,-0.306610,-0.241218,-0.334759,-0.688215,1.466943,-0.02399,0.968181
2589,-0.732770,-0.822163,-0.153063,-0.333105,0.467861,-0.231737,-0.270626,-0.263003,-0.056142,-0.569867,...,-0.317487,0.652521,-0.313741,-0.306610,-0.241218,-0.334759,1.453035,-0.681690,-0.02399,-1.032865
8302,1.364685,-0.055109,-0.153063,-0.333105,-0.281027,-0.283579,-0.270626,-0.263003,-0.541982,1.754795,...,-0.317487,-1.532519,-0.313741,3.261474,-0.241218,-0.334759,-0.688215,-0.681690,-0.02399,0.968181
8177,-0.732770,-0.612966,-0.153063,-0.333105,-0.279773,0.199721,0.596546,-0.263003,2.363185,-0.569867,...,-0.317487,0.652521,-0.313741,-0.306610,-0.241218,-0.334759,1.453035,-0.681690,-0.02399,-1.032865
500,1.364685,0.502749,-0.153063,-0.333105,-0.281027,-0.283579,-0.270626,-0.263003,-1.156195,1.754795,...,-0.317487,-1.532519,-0.313741,3.261474,-0.241218,-0.334759,-0.688215,-0.681690,-0.02399,-1.032865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5734,-0.732770,-0.752431,-0.153063,-0.311908,-0.279773,-0.042765,0.271356,-0.263003,0.759517,-0.569867,...,-0.317487,0.652521,-0.313741,-0.306610,-0.241218,-0.334759,-0.688215,1.466943,-0.02399,0.968181
5191,-0.732770,1.478999,-0.153063,0.711588,-0.281027,-0.233409,0.406408,0.114401,0.907639,-0.569867,...,-0.317487,0.652521,-0.313741,-0.306610,-0.241218,-0.334759,1.453035,-0.681690,-0.02399,0.968181
5390,-0.732770,-0.473502,-0.153063,-0.093885,-0.281027,0.512444,-0.270626,-0.240077,1.166359,-0.569867,...,3.149739,-1.532519,-0.313741,-0.306610,-0.241218,-0.334759,1.453035,-0.681690,-0.02399,-1.032865
860,-0.732770,0.363284,-0.153063,0.240720,-0.281027,2.435609,-0.270626,-0.263003,-0.814527,-0.569867,...,-0.317487,0.652521,-0.313741,-0.306610,-0.241218,-0.334759,1.453035,-0.681690,-0.02399,-1.032865
7270,-0.732770,-0.055109,-0.153063,-0.322506,0.025422,-0.283579,-0.267072,5.051525,-0.692079,1.754795,...,-0.317487,-1.532519,-0.313741,3.261474,-0.241218,-0.334759,-0.688215,-0.681690,-0.02399,-1.032865

### Neural Network

In [ ]:
import torch

# convert data to tensors
X_train_tensor = torch.tensor (X_train.values, dtype = torch.float32)
X_val_tensor = torch.tensor (X_val.values, dtype = torch.float32)
y_train_tensor = torch.tensor (y_train.values, dtype = torch.float32).view (-1, 1)
y_val_tensor = torch.tensor (y_val.values, dtype = torch.float32).view (-1, 1)

# model
class NeuralNetRegressor (torch.nn.Module):
    def __init__ (self, input_size):
        super ().__init__ ()

        self.linear1 = torch.nn.Linear (input_size, 32)
        self.linear2 = torch.nn.Linear (32, 16)
        self.linear3 = torch.nn.Linear (16, 8)
        self.linear4 = torch.nn.Linear (8, 1)

        self.relu = torch.nn.ReLU ()
    
    def forward (self, x):
        x = self.relu (self.linear1 (x))
        x = self.relu (self.linear2 (x))
        x = self.relu (self.linear3 (x))
        x = self.linear4 (x)
        return x
    
model = NeuralNetRegressor (input_size = X_scaled.shape [1])

# optimizer, loss using binary cross entropy
optimizer = torch.optim.Adam (model.parameters (), lr = 0.001)
loss_function = torch.nn.BCEWithLogitsLoss ()

# training model
n_epoch = 2000

for epoch in range (n_epoch):
    optimizer.zero_grad ()

    y_pred_train = model (X_train_tensor)
    loss = loss_function (y_pred_train, y_train_tensor)

    loss.backward ()
    optimizer.step ()

    # compute accuracy
    model.eval ()
    with torch.no_grad ():
        y_pred_val = model (X_val_tensor)
        probs_val = torch.sigmoid (y_pred_val) # convert logits into probability
        predicted_val = (probs_val >= 0.5).float ()     # convert probability into class 0 or 1
        val_accuracy = (predicted_val == y_val_tensor).float ().mean ()     # compare with actua; values

    if epoch % 1000 == 0 or epoch == n_epoch - 1:
            model.eval()
            with torch.no_grad():
                train_preds = (torch.sigmoid(model(X_train_tensor)) >= 0.5).float()
                train_acc = (train_preds == y_train_tensor).float().mean()
            print(f"Epoch {epoch} | Loss: {loss.item():.4f} | Train Accuracy: {train_acc.item():.4f} | Val Accuracy: {val_accuracy.item():.4f}")

Epoch 0 | Loss: 0.7038 | Train Accuracy: 0.4967 | Val Accuracy: 0.4951
Epoch 1000 | Loss: 0.3030 | Train Accuracy: 0.8559 | Val Accuracy: 0.7826
Epoch 2000 | Loss: 0.2797 | Train Accuracy: 0.8714 | Val Accuracy: 0.7711